'use strict';
const path=require('path');const {ensureDir,readJson,atomicJson,now,uuid}=require('./jsonfs');
class JsonGraphStore{
  constructor(engine,name='default'){this.engine=engine;this.name=name;this.root=path.join(engine.data,'advanced','graph',name);this.nodesFile=path.join(this.root,'nodes.json');this.edgesFile=path.join(this.root,'edges.json');this.adjFile=path.join(this.root,'adjacency.json')}
  async init(){await ensureDir(this.root);if(!(await readJson(this.nodesFile,null)))await atomicJson(this.nodesFile,{nodes:{}});if(!(await readJson(this.edgesFile,null)))await atomicJson(this.edgesFile,{edges:{}});if(!(await readJson(this.adjFile,null)))await atomicJson(this.adjFile,{out:{},in:{},builtAt:now()});return this.status()}
  async nodes(){return readJson(this.nodesFile,{nodes:{}})}async edges(){return readJson(this.edgesFile,{edges:{}})}
  async rebuild(){const e=await this.edges();const adj={out:{},in:{},builtAt:now()};for(const edge of Object.values(e.edges)){(adj.out[edge.from]||=[]).push(edge.id);(adj.in[edge.to]||=[]).push(edge.id);if(!edge.directed){(adj.out[edge.to]||=[]).push(edge.id);(adj.in[edge.from]||=[]).push(edge.id)}}await atomicJson(this.adjFile,adj);return adj}
  async addNode(label,properties={},id=null){const store=await this.nodes();id=id||uuid();if(store.nodes[id])throw Object.assign(new Error('Graph node exists.'),{status:409});store.nodes[id]={id,label:String(label||'Node'),properties,createdAt:now()};await atomicJson(this.nodesFile,store);return store.nodes[id]}
  async addEdge(from,to,type='RELATED_TO',properties={},directed=true){const n=await this.nodes();if(!n.nodes[from]||!n.nodes[to])throw Object.assign(new Error('Both graph nodes must exist.'),{status:409});const store=await this.edges();const id=uuid();store.edges[id]={id,from,to,type:String(type),directed:Boolean(directed),properties,createdAt:now()};await atomicJson(this.edgesFile,store);await this.rebuild();return store.edges[id]}
  async neighbors(nodeId,direction='out',type=null){const [nodes,edges,adj]=await Promise.all([this.nodes(),this.edges(),readJson(this.adjFile,{out:{},in:{}})]);const ids=direction==='in'?(adj.in[nodeId]||[]):direction==='both'?[...new Set([...(adj.out[nodeId]||[]),...(adj.in[nodeId]||[])])]:adj.out[nodeId]||[];const result=[];for(const id of ids){const e=edges.edges[id];if(!e||(type&&e.type!==type))continue;const other=e.from===nodeId?e.to:e.from;result.push({edge:e,node:nodes.nodes[other]})}return result}
  async shortestPath(start,target,maxDepth=12){if(start===target)return{found:true,path:[start],depth:0};const queue=[[start]];const seen=new Set([start]);let examined=0;while(queue.length){const pathNow=queue.shift();if(pathNow.length-1>=maxDepth)continue;const last=pathNow[pathNow.length-1];for(const item of await this.neighbors(last,'out')){examined++;const next=item.node?.id;if(!next||seen.has(next))continue;const p=[...pathNow,next];if(next===target)return{found:true,path:p,depth:p.length-1,examined};seen.add(next);queue.push(p)}}return{found:false,path:[],examined,maxDepth}}
  async traverse(start,{direction='out',type=null,maxDepth=3,maxNodes=500}={}){const queue=[{id:start,depth:0}];const seen=new Set();const output=[];while(queue.length&&output.length<maxNodes){const current=queue.shift();if(seen.has(current.id))continue;seen.add(current.id);output.push(current);if(current.depth>=maxDepth)continue;for(const item of await this.neighbors(current.id,direction,type))if(item.node&&!seen.has(item.node.id))queue.push({id:item.node.id,depth:current.depth+1,via:item.edge.type})}return{start,direction,type,maxDepth,nodes:output}}
  async pageRank(iterations=20,damping=.85){const nodes=await this.nodes();const ids=Object.keys(nodes.nodes);if(!ids.length)return{scores:{}};let scores=Object.fromEntries(ids.map(id=>[id,1/ids.length]));for(let iter=0;iter<iterations;iter++){const next=Object.fromEntries(ids.map(id=>[id,(1-damping)/ids.length]));for(const id of ids){const neighbors=await this.neighbors(id,'out');if(!neighbors.length){for(const target of ids)next[target]+=damping*scores[id]/ids.length;continue}for(const item of neighbors)next[item.node.id]+=damping*scores[id]/neighbors.length}scores=next}return{iterations,damping,scores:Object.fromEntries(Object.entries(scores).sort((a,b)=>b[1]-a[1]))}}
  async importCollection(collection,labelField='id',edges=[]){const rows=await this.engine.readAt(collection);const nodeStore=await this.nodes();let added=0;for(const row of rows){const id=`${collection}:${row.id}`;if(!nodeStore.nodes[id]){nodeStore.nodes[id]={id,label:String(row[labelField]??collection),properties:row,createdAt:now(),source:{collection,rowId:row.id}};added++}}await atomicJson(this.nodesFile,nodeStore);let edgeCount=0;for(const spec of edges){for(const row of rows){const target=row[spec.field];if(!target)continue;const targetId=`${spec.targetCollection||collection}:${target}`;if(nodeStore.nodes[targetId]){await this.addEdge(`${collection}:${row.id}`,targetId,spec.type||spec.field,{},true);edgeCount++}}}return{collection,nodesAdded:added,edgesAdded:edgeCount}}
  async status(){const [n,e]=await Promise.all([this.nodes(),this.edges()]);return{name:this.name,nodes:Object.keys(n.nodes).length,edges:Object.keys(e.edges).length}}
}
module.exports={JsonGraphStore};
