'use strict';

const crypto=require('crypto');const {canonical}=require('./truth');
function get(o,f){return String(f||'').split('.').reduce((v,k)=>v==null?undefined:v[k],o)}
function pred(n,row){if(!n)return true;if(n.and)return n.and.every(x=>pred(x,row));if(n.or)return n.or.some(x=>pred(x,row));if(n.not)return!pred(n.not,row);const a=get(row,n.field),b=n.value,op=n.op||'eq';if(op==='eq')return a===b;if(op==='ne')return a!==b;if(op==='gt')return a>b;if(op==='gte')return a>=b;if(op==='lt')return a<b;if(op==='lte')return a<=b;if(op==='in')return Array.isArray(b)&&b.includes(a);if(op==='nin')return Array.isArray(b)&&!b.includes(a);if(op==='contains')return String(a??'').toLowerCase().includes(String(b??'').toLowerCase());if(op==='startsWith')return String(a??'').toLowerCase().startsWith(String(b??'').toLowerCase());if(op==='endsWith')return String(a??'').toLowerCase().endsWith(String(b??'').toLowerCase());if(op==='exists')return b?a!==undefined:a===undefined;if(op==='regex'){try{return new RegExp(String(b),'i').test(String(a??''))}catch{return false}}throw new Error(`reference evaluator unsupported op ${op}`)}
function nestedJoin(left,right,spec){const out=[],alias=spec.as||spec.collection,type=spec.type||'inner';for(const l of left){let hits=0;for(const r of right)if(get(l,spec.on.left)===get(r,spec.on.right)){out.push({...l,[alias]:r});hits++}if(!hits&&type==='left')out.push({...l,[alias]:null})}return out}
function aggregate(rows,groupBy=[],aggregates={}){if(!groupBy.length&&!Object.keys(aggregates).length)return rows;const groups=new Map();for(const row of rows){const vals=groupBy.map(f=>get(row,f)),k=JSON.stringify(vals);if(!groups.has(k))groups.set(k,{vals,rows:[]});groups.get(k).rows.push(row)}if(!groupBy.length)groups.set('[]',{vals:[],rows});const out=[];for(const g of groups.values()){const row={};groupBy.forEach((f,i)=>row[f]=g.vals[i]);for(const[alias,spec]of Object.entries(aggregates)){const vals=spec.field?g.rows.map(r=>get(r,spec.field)).filter(v=>v!=null):[];if(spec.op==='count'||!spec.op)row[alias]=spec.field?vals.length:g.rows.length;else if(spec.op==='sum')row[alias]=vals.reduce((a,b)=>a+Number(b||0),0);else if(spec.op==='avg')row[alias]=vals.length?vals.reduce((a,b)=>a+Number(b||0),0)/vals.length:null;else if(spec.op==='min')row[alias]=vals.length?vals.reduce((a,b)=>a<b?a:b):null;else if(spec.op==='max')row[alias]=vals.length?vals.reduce((a,b)=>a>b?a:b):null;else throw new Error(`reference aggregate unsupported ${spec.op}`)}out.push(row)}return out}
function order(rows,specs=[]){if(!specs?.length)return rows;return[...rows].sort((a,b)=>{for(const s of specs){const field=typeof s==='string'?s.replace(/^-/,''):s.field,dir=typeof s==='string'&&s.startsWith('-')?-1:String(s.direction||'asc').toLowerCase()==='desc'?-1:1,av=get(a,field),bv=get(b,field);if(av===bv)continue;return(av>bv?1:-1)*dir}return 0})}
function project(rows,select){if(!select?.length||select.includes('*'))return rows;return rows.map(r=>Object.fromEntries(select.map(f=>[f,get(r,f)])))}
function hashRows(rows,ordered){const normalized=rows.map(canonical);if(!ordered)normalized.sort((a,b)=>JSON.stringify(a).localeCompare(JSON.stringify(b)));return crypto.createHash('sha256').update(JSON.stringify(normalized)).digest('hex')}

class MetamorphicVerifier{
 constructor(engine,savior=null){this.engine=engine;this.savior=savior}
 async reference(query){if(query.asOf!=null)throw new Error('Metamorphic reference path currently verifies latest-state queries only.');let rows=[...(await this.engine.loadCurrent(query.from)).rows];const examined={base:rows.length,joins:[]};rows=rows.filter(r=>pred(query.where,r));for(const join of query.joins||[]){const right=[...(await this.engine.loadCurrent(join.collection)).rows];examined.joins.push({collection:join.collection,rows:right.length,algorithm:'nested-loop-reference'});rows=nestedJoin(rows,right,join)}rows=aggregate(rows,query.groupBy||[],query.aggregates||{});if(query.having)rows=rows.filter(r=>pred(query.having,r));rows=order(rows,query.orderBy||[]);const total=rows.length,offset=Math.max(0,Number(query.offset||0)),limit=Math.min(5000,Math.max(1,Number(query.limit||100)));rows=project(rows.slice(offset,offset+limit),query.select||['*']);return{rows,total,offset,limit,explain:{access:'full-scan-reference',examined}}}
 async verify(query,options={}){const optimized=await this.engine.query(query),reference=await this.reference(query),ordered=Boolean(query.orderBy?.length),optimizedHash=hashRows(optimized.rows,ordered),referenceHash=hashRows(reference.rows,ordered),match=optimizedHash===referenceHash&&optimized.total===reference.total;const result={format:'JSONDB-METAMORPHIC-QUERY-1',match,optimizedHash,referenceHash,optimizedTotal:optimized.total,referenceTotal:reference.total,optimizedExplain:optimized.explain,referenceExplain:reference.explain};if(!match&&this.savior&&options.freezeOnMismatch!==false)await this.savior.setMode('read-only',`Metamorphic query disagreement: ${optimizedHash.slice(0,12)} != ${referenceHash.slice(0,12)}`);return result}
}
module.exports={MetamorphicVerifier,pred,nestedJoin,hashRows};
