'use strict';
const path=require('path');const {ensureDir,atomicJson,readJson,now}=require('./jsonfs');const{get}=require('./query');
function haversine(a,b){const R=6371;const rad=x=>x*Math.PI/180;const dLat=rad(b.lat-a.lat),dLon=rad(b.lon-a.lon);const x=Math.sin(dLat/2)**2+Math.cos(rad(a.lat))*Math.cos(rad(b.lat))*Math.sin(dLon/2)**2;return 2*R*Math.asin(Math.sqrt(x))}
function cell(lat,lon,precision=100){return`${Math.floor((lat+90)*precision)}:${Math.floor((lon+180)*precision)}`}
class JsonSpatialIndex{
 constructor(engine){this.engine=engine;this.root=path.join(engine.data,'advanced','spatial')}
 file(collection,name){return path.join(this.root,collection,`${name}.json`)}
 async build(collection,name,latField='lat',lonField='lon',precision=100){const rows=await this.engine.readAt(collection);const cells={},points={};let count=0;for(const row of rows){const lat=Number(get(row,latField)),lon=Number(get(row,lonField));if(!Number.isFinite(lat)||!Number.isFinite(lon)||lat< -90||lat>90||lon< -180||lon>180)continue;const c=cell(lat,lon,precision);(cells[c]||=[]).push(row.id);points[row.id]={lat,lon};count++}const index={type:'uniform-grid-spatial-index',collection,name,latField,lonField,precision,builtAt:now(),points,cells};await ensureDir(path.dirname(this.file(collection,name)));await atomicJson(this.file(collection,name),index);return{collection,name,points:count,cells:Object.keys(cells).length,precision}}
 async bbox(collection,name,minLat,minLon,maxLat,maxLon,limit=1000){const index=await readJson(this.file(collection,name),null);if(!index)throw Object.assign(new Error('Spatial index not built.'),{status:404});const minCellLat=Math.floor((Number(minLat)+90)*index.precision),maxCellLat=Math.floor((Number(maxLat)+90)*index.precision),minCellLon=Math.floor((Number(minLon)+180)*index.precision),maxCellLon=Math.floor((Number(maxLon)+180)*index.precision);const ids=new Set();for(let y=minCellLat;y<=maxCellLat;y++)for(let x=minCellLon;x<=maxCellLon;x++)for(const id of index.cells[`${y}:${x}`]||[])ids.add(id);const rows=(await this.engine.readAt(collection)).filter(row=>{if(!ids.has(row.id))return false;const p=index.points[row.id];return p.lat>=minLat&&p.lat<=maxLat&&p.lon>=minLon&&p.lon<=maxLon}).slice(0,limit);return{collection,index:name,bbox:{minLat,minLon,maxLat,maxLon},candidateIds:ids.size,rows}}
 async nearest(collection,name,lat,lon,k=10){const index=await readJson(this.file(collection,name),null);if(!index)throw Object.assign(new Error('Spatial index not built.'),{status:404});const origin={lat:Number(lat),lon:Number(lon)};const ranked=Object.entries(index.points).map(([id,p])=>({id,distanceKm:haversine(origin,p)})).sort((a,b)=>a.distanceKm-b.distanceKm).slice(0,Math.min(100,k));const map=new Map(ranked.map(x=>[x.id,x.distanceKm]));const rows=(await this.engine.readAt(collection)).filter(r=>map.has(r.id)).map(row=>({distanceKm:map.get(row.id),row})).sort((a,b)=>a.distanceKm-b.distanceKm);return{collection,index:name,origin,algorithm:'grid metadata + exact haversine ranking',rows}}
}
module.exports={JsonSpatialIndex,haversine};
