#!/usr/bin/env node
'use strict';

const path=require('path');const fs=require('fs');
const {MonsterEngine}=require('./monster/engine');const {SaviorSystem}=require('./monster/savior');const {TemporalQuorumGuardian}=require('./monster/guardian');const {OrthogonalArk}=require('./monster/orthogonal');const {WitnessCouncil}=require('./monster/witnesses');const {SurvivorGenome}=require('./monster/genome');const {TrinityArk}=require('./monster/trinity');const {FractalQuorum}=require('./monster/fractal');const {MetamorphicVerifier}=require('./monster/metamorphic');
const engine=new MonsterEngine(__dirname),savior=new SaviorSystem(engine,{cells:5}),guardian=new TemporalQuorumGuardian(savior),orthogonal=new OrthogonalArk(engine,savior),council=new WitnessCouncil(path.join(savior.root,'witness-council'),7,5),genome=new SurvivorGenome({engine,savior,orthogonal,council}),trinity=new TrinityArk(engine,savior),fractal=new FractalQuorum(savior),metamorphic=new MetamorphicVerifier(engine,savior);
async function boot(){await engine.init();await savior.init();await guardian.init();await orthogonal.init();await council.init();await genome.init();await trinity.init();await fractal.init()}function out(v){console.log(JSON.stringify(v,null,2))}function spec(file){return JSON.parse(fs.readFileSync(path.resolve(file),'utf8'))}function usage(){console.log(`JSONDB DOOMSDAY CLI\n\n  trinity-archive [label]\n  trinity-verify [id]\n  trinity-restore <output> [id] [--allow-degraded]\n  genome-create [label]\n  genome-verify\n  genome-extract <directory>\n  fractal <mirror-relative-table-path>\n  metamorphic <query.json>\n`)}
async function main(){await boot();const[cmd,...args]=process.argv.slice(2);if(!cmd)return usage();if(cmd==='trinity-archive')return out(await trinity.archive(args[0]||'doomsday'));if(cmd==='trinity-verify'){const r=await trinity.verify(args[0]||null);delete r._buffers;return out(r)}if(cmd==='trinity-restore')return out(await trinity.restore(path.resolve(args[0]||`trinity-restored-${Date.now()}.json`),args[1]&&!args[1].startsWith('--')?args[1]:null,{allowDegraded:args.includes('--allow-degraded')}));if(cmd==='genome-create')return out(await genome.create(args[0]||'doomsday'));if(cmd==='genome-verify')return out(await genome.verify());if(cmd==='genome-extract')return out(await genome.extract(path.resolve(args[0]||`recovery-source-${Date.now()}`)));if(cmd==='fractal')return out(await fractal.reconstruct(args[0]||'current/tasks.json'));if(cmd==='metamorphic')return out(await metamorphic.verify(spec(args[0]),{freezeOnMismatch:true}));usage();process.exitCode=2}
main().catch(e=>{console.error(e.stack||e);process.exitCode=1});
